name = "global-rankings-astro"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

# KV bindings for session storage
[[kv_namespaces]]
binding = "SESSION"
id = "your_kv_namespace_id"
preview_id = "your_preview_kv_namespace_id"

[[env.production]]
name = "global-rankings-astro"

[[env.production.vars]]
# Environment variables for production
NODE_ENV = "production"

# Add your environment variables here for Cloudflare Pages
# These should be set in the Cloudflare Pages dashboard
# PUBLIC_SUPABASE_URL = "your_production_supabase_url"
# PUBLIC_SUPABASE_ANON_KEY = "your_production_supabase_anon_key"
